### ISSUE TITLE
Plugin conflict with SEOmatic 

### ISSUE THREAD

**Issue by daniellefrapp** [charliedevelopment/craft3-fallback-site#3]
There seems to be a plugin conflict with Fallback site and SEOmatic, when I have fallback site turned on and I try to go to one of my sitemaps or robots.txt generated by SEOmatic I get a 404. All works as expected when I disable Fallback site.

**Comment by sbossarte** [comment]
The issue has two parts:

Fallback Site ran its initialization immediately when loaded. This uses Craft's UrlManager, and caused any plugin loaded afterwards to not be able to receive events from the `UrlManager`, such as `EVENT_REGISTER_CP_URL_RULES`, and `EVENT_REGISTER_SITE_URL_RULES`. Instead, will now run its initialization on the `EVENT_AFTER_LOAD_PLUGINS` event, ensuring other plugins have the chance to add their event handlers before initializing. This change has been made in https://github.com/charliedevelopment/craft3-fallback-site/commit/92fe44fe7014ef3e4f93d4067e7b1fd5f877ca9f

SEOmatic waits until the `EVENT_AFTER_LOAD_PLUGINS` event to add event handlers to the `UrlManager`, but this will _always_ happen after Fallback Site, because they are loaded, and their events fire, in alphabetical order. Instead, attaching event handlers to the `UrlManager` would need to be moved to the plugin's own `init()` method as well, instead of happening as late as it does.

**Comment by sbossarte** [comment]
I'd discussed the issue with @khalwat when this issue was opened. It's been a while, but right now the ball is in SEOmatic's court to update the event timing. While Fallback Site could be forced to trigger even later, that would simply be glossing over the underlying problem.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-seomatic/commit/e90a88b57d7f701a2c57b19c5589d2757a97131d and https://github.com/nystudio107/craft-seomatic/commit/98f3ea643e9efad30792ad6a84bf37026b4f6fec
